use_frameworks!

platform :ios, '11.0'

target 'WJCamera_Example' do
  pod 'WJCamera', :path => '../'

  target 'WJCamera_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
